services:

  api:
    build: .
    # volumes:
    #   - ./../ai-engine/src/ai_engine:/app/ai_engine
    # env_file:
    #   - .env
    container_name: ai_engine_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    # Assuming your Dockerfile CMD is:
    # CMD ["uvicorn", "ai_engine_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: ai_engine_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"               # so you can connect with psql locally
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: ai_engine_pgadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"   # host:container
volumes:
  db_data:
